apiVersion: v2
name: teamcity
description: A TeamCity Helm chart for Kubernetes
type: application
version: 2.3.1
appVersion: "2022.10.1"
dependencies:
  - name: server
    version: 2.3.1
#    repository: "https://strangerxxx.github.io/teamcity-helm"
    repository: "file://../server"
    condition: server.enabled
  - name: agent
    version: 2.3.1
#    repository: "https://strangerxxx.github.io/teamcity-helm"
    repository: "file://../agent"
    condition: agent.enabled
