apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-config
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  {{- include "server.config" . | nindent 2 }}
